joinRaidEvent = "Присоединиться к рейду:dagger_knife:"
raidStartsPrefix = "Битва начнётся через"
hoursShort = "ч."
minutesShort = "мин."
successJoinEvent = "Вы успешно присоединились к событию!"
"Да начнется битва!",
"Скоро прольется кровь!",
"Квест принят - вперед!",
userAlreadyInThisEvent = "Вы уже участвуете в данном событии!"
"Квест был принят, память подводит?",
"Вы уже участвуйте в походе.",
"В процессе выслеживания брага!"
userAlreadyInOtherEvent = "Вы уже участвуете в другом событии!"
"На двух квестах не усидишь!"
"Тебя разорвет от двух квестов сразу!"
"Вы еще не все задания завершили!"
expiredEvent = "Событие завершилось!"
"Конец квеста!"
successRaid = "Рейд был успешен."
"Ура, победа!"
"Враг был побежден"
"Зачистка прошла успешно!"
failureRaid = "Искатели провалили рейд."
"Эх, поражение."
"В следующий раз вы постараетесь лучше!"
"Наберитесь сил и возвращайтесь."
